plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.kotlin.ksp)
    id 'maven-publish'
}

android {
    namespace 'com.xiaojinzi.module.common.ffmpeg'
}

apply from: project.getRootProjectPath() + "/common_module.gradle"

ksp {
    arg("ModuleName", "module_common_ffmpeg")
}

dependencies {
    //noinspection UseTomlInstead
    implementation 'com.github.microshow:RxFFmpeg:4.9.0-lite'
}

apply from: "../common_publish.gradle"
