plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.kotlin.ksp)
    id 'maven-publish'
}

android {
    namespace 'com.xiaojinzi.module.common.wx.sdk'
}

apply from: project.getRootProjectPath() + "/common_module.gradle"

ksp {
    arg("ModuleName", "module_common_wx_sdk")
}

dependencies {
    // 这里必须 api, 因为使用的地方要继承的时候, 会检测能不能依赖到某个类
    //noinspection UseTomlInstead
    api 'com.tencent.mm.opensdk:wechat-sdk-android:6.8.11'
}

apply from: "../common_publish.gradle"
