plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.kotlin.ksp)
    id 'maven-publish'
}

android {
    namespace 'com.xiaojinzi.module.common.base'
}

apply from: getRootProjectPath() + "/common_android.gradle"
apply from: getRootProjectPath() + "/common_ksp_for_component.gradle"

ksp {
    arg("ModuleName", "module_common_base")
}

dependencies {
    api project(':lib-resource')
    ksp libs.component.compiler
    api libs.kotlin.stdlib
    api libs.kotlin.android.extensions.runtime
    api libs.kotlinx.coroutines.core.jvm
    api libs.kotlinx.coroutines.rx2

    api libs.androidx.core.ktx
    api libs.androidx.fragment.ktx
    api libs.androidx.emoji2
    api libs.androidx.emoji2.views
    api libs.androidx.emoji2.views.helper
    api libs.androidx.appcompat
    api libs.androidx.swiperefreshlayout
    api libs.androidx.compose.material
    api libs.androidx.compose.material3
    api libs.androidx.compose.constraintlayout
    api libs.androidx.compose.ui.foundation
    api libs.androidx.drawerlayout
    api libs.androidx.compose.constraintlayout
    api libs.androidx.lifecycle.runtime.ktx
    api libs.androidx.lifecycle.viewmodel.ktx

    api libs.androidx.page3.runtime
    api libs.androidx.page3.compose

    api libs.androidx.room
    api libs.androidx.room.ktx
    api libs.androidx.room.rxjava
    ksp libs.androidx.room.compiler

    // compose
    api platform(libs.androidx.compose.bom)
    api libs.androidx.activity.compose
    api libs.androidx.compose.viewmodel
    api libs.androidx.compose.ui
    api libs.androidx.compose.material
    api libs.androidx.compose.ui.tooling
    api libs.androidx.compose.ui.tooling.preview
    api libs.androidx.compose.constraintlayout

    api libs.component.impl
    api libs.support.init
    api libs.support.annotation
    api libs.support.ktx
    api libs.support.logger
    api libs.support.download
    api libs.support.architecture
    api libs.support.compose
    api libs.rxjava2.rxkotlin
    api libs.gson
    api libs.retrofit
    api libs.retrofit.converter.gson
    api libs.baseAdapter
    api libs.glide
    api libs.lottie.compose
    api libs.coil.svg
    api libs.coil.gif
    api libs.coil.video
    api libs.coil.compose
    api libs.kotlin.flow.extensions

    api libs.exoplayer.core
    api libs.exoplayer.ui

    api libs.accompanist.permissions

}

apply from: "../common_publish.gradle"

