plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.kotlin.ksp)
    id 'maven-publish'
}

android {
    namespace 'com.xiaojinzi.module.common.ali.oss'
}

apply from: project.getRootProjectPath() + "/common_module.gradle"

ksp {
    arg("ModuleName", "module_common_ali_oss")
}

dependencies {
    // 依赖 ali oss
    // noinspection UseTomlInstead
    implementation 'com.aliyun.dpa:oss-android-sdk:2.9.19'
}

apply from: "../common_publish.gradle"
