plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    id 'maven-publish'
}

android {
    namespace 'com.xiaojinzi.lib.common.res'
}

apply from: getRootProjectPath() + "/common_android_lib.gradle"

dependencies {
    api libs.support.bean
    api libs.support.annotation
    api libs.support.ktx
}

apply from: "../common_publish.gradle"
