plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.kotlin.ksp)
    id 'maven-publish'
}

android {
    namespace 'com.xiaojinzi.module.common.ali.pay'
}

apply from: project.getRootProjectPath() + "/common_module.gradle"

ksp {
    arg("ModuleName", "module_common_ali_pay")
}

dependencies {
    //noinspection UseTomlInstead
    implementation 'com.alipay.sdk:alipaysdk-android:15.8.11@aar'
}

apply from: "../common_publish.gradle"
